### ISSUE TITLE
Gatys 2017 content image download is broken

### ISSUE THREAD

**Issue by pmeier** [pystiche/papers#281]
The image 

https://github.com/pystiche/papers/blob/36213e573fa98f2ceece9ba18b0899d19e6ab760/pystiche_papers/gatys_et_al_2017/_data.py#L33-L37

is no longer accessible. The [shop link](https://de.aliexpress.com/item/1705231003.html) still features it as thumbnail, but there is no direct link. Not sure what do to about it. I have the image locally, so in theory we could host it, but that is a copyright violation. Not sure if there are exemptions for research here. cc @jbueltemeier

**Comment by jbueltemeier** [comment]
This is bad. Because a different image for replication is not so good for comparison. So I would look for another source for this image.  As the copyright should not be violated.

Can you remember where the masks for this image came from? Normally, the style image should be found there as well?!

**Comment by pmeier** [comment]
> So I would look for another source for this image.

I did and it seems there is none :confounded: Please also have look.

> As the copyright should not be violated.

Agreed. Could you ask in your research group if someone knows if there is such a thing as "exemptions" for research purposes? The problem here is not usage, but rather distribution.

I've contacted the shop owner to maybe get a license from them, but so far no response.

> Can you remember where the masks for this image came from?

I created them manually:

https://github.com/pystiche/papers/blob/36213e573fa98f2ceece9ba18b0899d19e6ab760/pystiche_papers/gatys_et_al_2017/_data.py#L41-L56

**Comment by jbueltemeier** [comment]
> I did and it seems there is none 😖 Please also have look.

I had in mind that the masks were available somewhere ([House Mask](https://github.com/leongatys/NeuralImageSynthesis/blob/master/Images/ControlPaper/fig2_style1_nosky.jpg)). Fortunately, the [style image](https://github.com/leongatys/NeuralImageSynthesis/blob/master/Images/ControlPaper/fig2_style1.jpg) is also available there. For the script, we should be able to use that.

> I've contacted the shop owner to maybe get a license from them, but so far no response.

I hope this is successful, otherwise I would suggest that this style image is not shown in the paper with an appropriate note. Since a corresponding "exemptions" should at least be included in the terms and conditions, which could be referred to. Due to the fact that in the current paper an exact listing with the images and the links has been integrated to be on the safe side because of the copyright.

**Comment by pmeier** [comment]
> I hope this is successful, otherwise I would suggest that this style image is not shown in the paper with an appropriate note.

I don't think just using an image for research purposes is big issue. Selfhosting it is a whole different beast. I think we should be fine, using a link to Gatys' repository. I'll send a PR.

In general though, I agree, part of the paper should also be how these images were obtained. Especially in cases like this it is another downside that they haven't used freely available images.
